language: python
python:
  - "2.7"
  # - "3.4" # 3.7 development branch
# command to install dependencies
install: "pip install -r requirements.txt"
install: "pip install coveralls"
install: "pip install nose2"
# command to run tests

before_script:
  - psql -c 'create database markerbot;' -U postgres
script: python manage.py db init
script: python manage.py db migrate
script: python manage.py db upgrade
script: coverage run --source=api --source=views --source=marker -m nose2.__main__ -v

services:
  - postgresql
after_success:
  - coveralls