language: python
python:
  - "2.7"
  # - "3.4" # 3.7 development branch
# command to install dependencies
install: "pip install -r requirements.txt"
install: "pip install coveralls"
# command to run tests

before_script:
  - psql -c 'create database markerbot;' -U postgres
script: python manage.py db init
script: python manage.py db migrate
script: python manage.py db upgrade
script: nose2 --with-cov --coverage-report term --coverage-report html --coverage views --coverage api --coverage marker

services:
  - postgresql
after_success:
  - coveralls