language: python
python:
  - "2.7" # 3.7 development branch
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: python manage.py db init
script: python manage.py db migrate
script: python manage.py db upgrade
script: nose2

services:
  - postgresql
